apiVersion: v1
version: 1.0.0
description: Installs the CRDs for rancher-compliance.
name: rancher-compliance-crd
type: application
annotations:
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/release-name: rancher-compliance-crd
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: rancher-compliance-system