workingDir: ""
url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/66.7.1-rancher.1/charts/prometheus-adapter
commit: 7324f005e61772c1614e36f2ee85ba9fb21a7ff8
ignoreDependencies: []
replacePaths: []
