url: https://github.com/rancher/backup-restore-operator/releases/download/v8.0.0-rc.2/rancher-backup-8.0.0-rc.2.tgz
version: 107.0.0
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/backup-restore-operator/releases/download/v8.0.0-rc.2/rancher-backup-crd-8.0.0-rc.2.tgz
