url: https://github.com/rancher/backup-restore-operator/releases/download/v6.0.2/rancher-backup-6.0.2.tgz
version: 105.0.3
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/backup-restore-operator/releases/download/v6.0.2/rancher-backup-crd-6.0.2.tgz
