url: https://github.com/rancher/backup-restore-operator/releases/download/v7.0.1/rancher-backup-7.0.1.tgz
version: 106.0.2
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/backup-restore-operator/releases/download/v7.0.1/rancher-backup-crd-7.0.1.tgz
