url: https://github.com/rancher/backup-restore-operator/releases/download/v5.0.3/rancher-backup-5.0.3.tgz
version: 104.0.3
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/backup-restore-operator/releases/download/v5.0.3/rancher-backup-crd-5.0.3.tgz
