{{- if .Values.alerts.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rancher-compliance-pod-monitor
  namespace: {{ template "app.namespace" . }}
spec:
  selector:
    matchLabels:
      compliance.cattle.io/operator: compliance-operator
  podMetricsEndpoints:
  - port: metrics
{{- end }}
