apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rancher-compliance
    app.kubernetes.io/instance: release-name
  name: compliance-operator-clusterrole
rules:
- apiGroups:
  - "compliance.cattle.io"
  resources:
  - "*"
  verbs:
  - "get"
  - "list"
  - "create"
  - "update"
  - "watch"
  - "patch"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "pods"
  - "services"
  - "configmaps"
  - "nodes"
  - "serviceaccounts"
  verbs:
  - "get"
  - "list"
  - "create"
  - "update"
  - "watch"
  - "patch"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "rolebindings"
  - "clusterrolebindings"
  - "clusterroles"
  - "roles"
  verbs:
  - "get"
  - "list"
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - "list"
  - "create"
  - "patch"
  - "update"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rancher-compliance
    app.kubernetes.io/instance: release-name
  name: compliance-scan
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "nodes"
  - "pods"
  - "serviceaccounts"
  - "services"
  - "replicationcontrollers"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups: 
  - "rbac.authorization.k8s.io"
  resources:
  - "rolebindings"
  - "clusterrolebindings"
  - "clusterroles"
  - "roles"
  verbs:
  - "get"
  - "list"
- apiGroups:
   - "batch"
  resources:
   - "jobs"
   - "cronjobs"
  verbs:
   - "list"
- apiGroups:
    - "apps"
  resources:
    - "daemonsets"
    - "deployments"
    - "replicasets"
    - "statefulsets"
  verbs:
    - "list"
- apiGroups:
    - "autoscaling"
  resources:
    - "horizontalpodautoscalers"
  verbs:
    - "list"
- apiGroups:
    - "networking.k8s.io"
  resources:
    - "networkpolicies"
  verbs:
    - "get"
    - "list"
    - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: compliance-operator-role
  labels:
    app.kubernetes.io/name: rancher-compliance
    app.kubernetes.io/instance: release-name
  namespace: {{ template "app.namespace" . }}
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  verbs:
  - "watch"
  - "list"
  - "get"
  - "patch"
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - "watch"
  - "list"
  - "get"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "configmaps"
  - "pods"
  - "secrets"
  verbs:
  - "*"
- apiGroups:
  - "apps"
  resources:
  - "daemonsets"
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rancher-compliance
    app.kubernetes.io/instance: release-name
  name: compliance-operator-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: compliance-operator-clusterrole
subjects:
- kind: ServiceAccount
  name: compliance-operator-serviceaccount
  namespace: {{ template "app.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: compliance-scan
  labels:
    app.kubernetes.io/name: rancher-compliance
    app.kubernetes.io/instance: release-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: compliance-scan
subjects:
- kind: ServiceAccount
  name: compliance-scan-serviceaccount
  namespace: {{ template "app.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rancher-compliance
    app.kubernetes.io/instance: release-name
  name: compliance-operator-rolebinding
  namespace: {{ template "app.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: compliance-operator-role
subjects:
- kind: ServiceAccount
  name: compliance-scan-serviceaccount
  namespace: {{ template "app.namespace" . }}
- kind: ServiceAccount
  name: compliance-operator-serviceaccount
  namespace: {{ template "app.namespace" . }}
