apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterscanreports.compliance.cattle.io
spec:
  group: compliance.cattle.io
  names:
    kind: ClusterScanReport
    plural: clusterscanreports
    singular: clusterscanreport
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.lastRunTimestamp
      name: LastRunTimestamp
      type: string
    - jsonPath: .spec.benchmarkVersion
      name: BenchmarkVersion
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              benchmarkVersion:
                nullable: true
                type: string
              lastRunTimestamp:
                nullable: true
                type: string
              reportJSON:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
