auto: true
url: https://github.com/rancher/eks-operator.git
chartRepoBranch: release-v2.11
subdirectory: charts/eks-operator
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/eks-operator.git
      chartRepoBranch: release-v2.11
      subdirectory: charts/eks-operator-crd/templates
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: false
