auto: true
url: https://github.com/rancher/eks-operator.git
chartRepoBranch: charts/v1.10
subdirectory: charts/rancher-eks-operator
workingDir: rancher-eks-operator
additionalCharts:
  - workingDir: rancher-eks-operator-crd
    upstreamOptions:
      url: https://github.com/rancher/eks-operator.git
      chartRepoBranch: charts/v1.10
      subdirectory: charts/rancher-eks-operator-crd