url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/66.7.1-rancher.10
commit: d1657cc2b3de0933aedec9dc9a913dd05f2caf97
version: 106.0.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/66.7.1-rancher.10
      commit: d1657cc2b3de0933aedec9dc9a913dd05f2caf97
doNotRelease: false
