url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/69.8.2-rancher.8
commit: df56966a054c012a13caa5f7a60aec6469b897db
version: 107.0.0-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/69.8.2-rancher.8
      commit: df56966a054c012a13caa5f7a60aec6469b897db
doNotRelease: false
