url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/66.7.1-rancher.6
commit: 8d6c1776047e22176446b712db35d0bbdfc737f5
version: 106.0.1-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/66.7.1-rancher.6
      commit: 8d6c1776047e22176446b712db35d0bbdfc737f5
doNotRelease: false
