url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/61.3.2-rancher.5
commit: 242e4bb194777288e931ce14fa94188aa9d74def
version: 105.1.4-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/61.3.2-rancher.5
      commit: 242e4bb194777288e931ce14fa94188aa9d74def
doNotRelease: false