url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/66.7.1-rancher.2
commit: bedf828291d0fff4e3b0bbf350ecc7b9834dd958
version: 106.0.0
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/66.7.1-rancher.2
      commit: bedf828291d0fff4e3b0bbf350ecc7b9834dd958
doNotRelease: false
