url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/66.7.1-rancher.8
commit: 8c535084fc32bd99891c5ea5da3913a1ddb1084a
version: 106.0.1-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/66.7.1-rancher.8
      commit: 8c535084fc32bd99891c5ea5da3913a1ddb1084a
doNotRelease: false
