url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/69.8.2-rancher.3
commit: 794f66d61320ee7fa9aebd085141b2998dbee519
version: 106.1.0-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/69.8.2-rancher.3
      commit: 794f66d61320ee7fa9aebd085141b2998dbee519
doNotRelease: false
