url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/66.7.1-rancher.1
commit: 7324f005e61772c1614e36f2ee85ba9fb21a7ff8
version: 106.0.0-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/66.7.1-rancher.1
      commit: 7324f005e61772c1614e36f2ee85ba9fb21a7ff8
doNotRelease: false
