url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/69.8.2-rancher.4
commit: 1308ba977839d187ccd664e4f676934c8b01a436
version: 106.1.0-rc.2
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/69.8.2-rancher.4
      commit: 1308ba977839d187ccd664e4f676934c8b01a436
doNotRelease: false
