auto: true
url: https://github.com/rancher/aks-operator.git
chartRepoBranch: charts/v1.11
subdirectory: charts/rancher-aks-operator
workingDir: rancher-aks-operator
additionalCharts:
  - workingDir: rancher-aks-operator-crd
    upstreamOptions:
      url: https://github.com/rancher/aks-operator.git
      chartRepoBranch: charts/v1.11
      subdirectory: charts/rancher-aks-operator-crd