apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterscanprofiles.compliance.cattle.io
spec:
  group: compliance.cattle.io
  names:
    kind: ClusterScanProfile
    plural: clusterscanprofiles
    singular: clusterscanprofile
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.benchmarkVersion
      name: BenchmarkVersion
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              benchmarkVersion:
                nullable: true
                type: string
              skipTests:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
