apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-operator
  namespace: {{ template "app.namespace" . }}
  labels:
    compliance.cattle.io/operator: compliance-operator
spec:
  selector:
    matchLabels:
      compliance.cattle.io/operator: compliance-operator
  template:
    metadata:
      labels:
        compliance.cattle.io/operator: compliance-operator
    spec:
      serviceAccountName: compliance-operator-serviceaccount
      containers:
      - name: compliance-operator
        image: '{{ template "system_default_registry" . }}{{ .Values.image.operator.repository }}:{{ .Values.image.operator.tag }}'
        imagePullPolicy: IfNotPresent
        ports:
        - name: metrics
          containerPort: {{ .Values.alerts.metricsPort }}
        env:
        - name: SECURITY_SCAN_IMAGE
          value: {{ template "system_default_registry" . }}{{ .Values.image.securityScan.repository }}
        - name: SECURITY_SCAN_IMAGE_TAG
          value: {{ .Values.image.securityScan.tag }}
        - name: SONOBUOY_IMAGE
          value: {{ template "system_default_registry" . }}{{ .Values.image.sonobuoy.repository }}
        - name: SONOBUOY_IMAGE_TAG
          value: {{ .Values.image.sonobuoy.tag }}
        - name: METRICS_PORT
          value: '{{ .Values.alerts.metricsPort }}'
        - name: ALERTS_SEVERITY
          value: {{ .Values.alerts.severity }}
        - name: ALERTS_ENABLED
          value: {{ .Values.alerts.enabled | default "false" | quote }}
        - name: CLUSTER_NAME
          value: '{{ .Values.global.cattle.clusterName }}'
        - name: OPERATOR_DEBUG
          value: '{{ .Values.debug }}'
        {{- if .Values.securityScanJob.overrideTolerations }}
        - name: SECURITY_SCAN_JOB_TOLERATIONS
          value: '{{ .Values.securityScanJob.tolerations | toJson  }}'
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector: {{ include "linux-node-selector" . | nindent 8 }}
{{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      tolerations: {{ include "linux-node-tolerations" . | nindent 8 }}
{{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
