---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compliance-admin
rules:
  - apiGroups:
      - compliance.cattle.io
    resources:
      - clusterscanbenchmarks
      - clusterscanprofiles
      - clusterscans
      - clusterscanreports
    verbs: ["create", "update", "delete", "patch","get", "watch", "list"]
  - apiGroups:
      - catalog.cattle.io
    resources: ["apps"]
    resourceNames: ["rancher-compliance"]
    verbs: ["get", "watch", "list"]
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs: ["create", "update", "delete", "patch","get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compliance-view
rules:
  - apiGroups:
      - compliance.cattle.io
    resources:
      - clusterscanbenchmarks
      - clusterscanprofiles
      - clusterscans
      - clusterscanreports
    verbs: ["get", "watch", "list"]
  - apiGroups:
      - catalog.cattle.io
    resources: ["apps"]
    resourceNames: ["rancher-compliance"]
    verbs: ["get", "watch", "list"]
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs: ["get", "watch", "list"]
