apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ template "app.namespace" . }}
  name: compliance-operator-serviceaccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ template "app.namespace" . }}
  labels:
    app.kubernetes.io/name: rancher-compliance
    app.kubernetes.io/instance: release-name
  name: compliance-scan-serviceaccount
