url: https://github.com/rancher/compliance-operator.git
version: 107.0.0
chartRepoBranch: main
subdirectory: chart
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/compliance-operator.git
      chartRepoBranch: main
      subdirectory: crds
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true