url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-logging/4.10.0-rancher.2
commit: 0e67984f49844da6c6476b766cacac1df23aff15
version: 106.0.1-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-logging-crd/4.10.0-rancher.2
      commit: 0e67984f49844da6c6476b766cacac1df23aff15
doNotRelease: false
