url: oci://ghcr.io/kube-logging/helm-charts/logging-operator:4.10.0
version: 105.2.1
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
doNotRelease: false
