url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-logging/4.10.0-rancher.1
commit: 07984096d3fa8d47228edd73278dd2956c4d7514
version: 106.0.0-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-logging-crd/4.10.0-rancher.1
      commit: 07984096d3fa8d47228edd73278dd2956c4d7514
doNotRelease: false
