url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-logging/4.10.0-rancher.1
commit: 76b822bf3c6c3b71b89836d98a97c690ee9fedda
version: 105.2.2-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-logging-crd/4.10.0-rancher.1
      commit: 76b822bf3c6c3b71b89836d98a97c690ee9fedda
doNotRelease: false
