url: oci://ghcr.io/kube-logging/helm-charts/logging-operator:4.8.0
version: 104.2.1-rc.1
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
doNotRelease: false
