url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-logging/4.10.0-rancher.4
commit: f5aac180bcfe15c036a3bb8f9f3365fe1e59b79e
version: 106.0.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-logging-crd/4.10.0-rancher.4
      commit: f5aac180bcfe15c036a3bb8f9f3365fe1e59b79e
doNotRelease: false
