url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-logging/4.10.0-rancher.4
commit: 794f66d61320ee7fa9aebd085141b2998dbee519
version: 105.3.0-rc1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-logging-crd/4.10.0-rancher.4
      commit: 794f66d61320ee7fa9aebd085141b2998dbee519
doNotRelease: false
