url: https://neuvector.github.io/neuvector-helm/core-2.8.6.tgz
version: 105.0.3
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
