url: https://neuvector.github.io/neuvector-helm/core-2.8.5.tgz
version: 104.0.5
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
