auto: true
url: https://github.com/rancher/gke-operator.git
chartRepoBranch: charts/v1.10
subdirectory: charts/rancher-gke-operator
workingDir: rancher-gke-operator
additionalCharts:
  - workingDir: rancher-gke-operator-crd
    upstreamOptions:
      url: https://github.com/rancher/gke-operator.git
      chartRepoBranch: charts/v1.10
      subdirectory: charts/rancher-gke-operator-crd